<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Automatio Test" duration-ms="5152" started-at="2016-04-06T16:08:24Z" finished-at="2016-04-06T16:08:29Z">
    <groups>
    </groups>
    <test name="Smoke Testcases" duration-ms="5152" started-at="2016-04-06T16:08:24Z" finished-at="2016-04-06T16:08:29Z">
      <class name="com.morningstar.test.SampleTest2">
        <test-method status="FAIL" signature="LoginApp()[pri:0, instance:com.morningstar.test.SampleTest2@5be24af0]" name="LoginApp" duration-ms="1" started-at="2016-04-06T16:08:29Z" data-provider="Loginpagedata" finished-at="2016-04-06T16:08:29Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
The data provider is trying to pass 1 parameters but the method com.morningstar.test.SampleTest2#LoginApp takes 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 1 parameters but the method com.morningstar.test.SampleTest2#LoginApp takes 0
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1325)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1213)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
        </test-method> <!-- LoginApp -->
      </class> <!-- com.morningstar.test.SampleTest2 -->
      <class name="com.morningstar.test.SampleTest">
        <test-method status="PASS" signature="cancelitinerary()[pri:0, instance:com.morningstar.test.SampleTest@155a792d]" name="cancelitinerary" duration-ms="5135" started-at="2016-04-06T16:08:24Z" finished-at="2016-04-06T16:08:29Z">
        </test-method> <!-- cancelitinerary -->
      </class> <!-- com.morningstar.test.SampleTest -->
    </test> <!-- Smoke Testcases -->
  </suite> <!-- Automatio Test -->
</testng-results>
